version: "3"
services:
  app:
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    build: .
    depends_on:
      - database
    ports:
      - "4000:4000"

  database:
    image: postgres:11.2-alpine
    container_name: database
    ports:
      - "54320:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
    driver: local